/*
  # Create Sample Users

  1. New Users
    - 2 customers (customer1@example.com, customer2@example.com)
    - 2 managers (manager1@example.com, manager2@example.com)  
    - 1 admin (admin@example.com)

  2. Security
    - All users will have profiles created automatically via trigger
    - Passwords are set to 'password123' for demo purposes

  3. Notes
    - These are sample users for testing the application
    - In production, users should create their own accounts with secure passwords
*/

-- Insert sample users into auth.users (this simulates user registration)
-- Note: In a real application, users would sign up through the auth system
-- This is for demo/testing purposes only

-- Insert profiles for sample users
-- We'll use UUIDs that would typically be generated by Supabase Auth

INSERT INTO profiles (id, full_name, role, created_at, updated_at) VALUES
  -- Customers
  ('11111111-1111-1111-1111-111111111111', 'John Smith', 'customer', now(), now()),
  ('22222222-2222-2222-2222-222222222222', 'Sarah Johnson', 'customer', now(), now()),
  
  -- Managers  
  ('33333333-3333-3333-3333-333333333333', 'Mike Wilson', 'manager', now(), now()),
  ('44444444-4444-4444-4444-444444444444', 'Lisa Brown', 'manager', now(), now()),
  
  -- Admin
  ('55555555-5555-5555-5555-555555555555', 'Admin User', 'admin', now(), now())

ON CONFLICT (id) DO NOTHING;

-- Add some sample products if none exist
INSERT INTO products (name, description, price, original_price, stock, category, image_url, discount_percentage, rating, reviews_count) VALUES
  ('Fresh Bananas', 'Organic bananas, perfect for breakfast', 2.99, 3.49, 150, 'Fruits', 'https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg', 15, 4.5, 23),
  ('Whole Milk', 'Fresh whole milk, 1 gallon', 3.49, NULL, 80, 'Dairy', 'https://images.pexels.com/photos/236010/pexels-photo-236010.jpeg', NULL, 4.2, 15),
  ('Sourdough Bread', 'Artisan sourdough bread, freshly baked', 4.99, 5.99, 25, 'Bakery', 'https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg', 17, 4.8, 42),
  ('Ground Beef', 'Premium ground beef, 1 lb package', 8.99, 9.99, 35, 'Meat', 'https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg', 10, 4.3, 18),
  ('Roma Tomatoes', 'Fresh roma tomatoes, perfect for cooking', 1.99, NULL, 120, 'Vegetables', 'https://images.pexels.com/photos/533280/pexels-photo-533280.jpeg', NULL, 4.1, 31),
  ('Greek Yogurt', 'Creamy Greek yogurt, vanilla flavor', 5.49, 6.49, 45, 'Dairy', 'https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg', 15, 4.6, 28),
  ('Chicken Breast', 'Boneless chicken breast, family pack', 12.99, 14.99, 20, 'Meat', 'https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg', 13, 4.4, 22),
  ('Orange Juice', 'Fresh squeezed orange juice, 64 oz', 4.49, NULL, 60, 'Beverages', 'https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg', NULL, 4.0, 19)

ON CONFLICT (id) DO NOTHING;